-- AlterTable
ALTER TABLE "RadioStatus" ADD COLUMN     "streamUrl" TEXT,
ALTER COLUMN "id" DROP DEFAULT,
ALTER COLUMN "live" DROP DEFAULT,
ALTER COLUMN "title" DROP NOT NULL,
ALTER COLUMN "title" DROP DEFAULT;
